all:
  children:
    windows:
      hosts:
        dc01:
          ansible_host: 10.0.20.60
          ansible_user: Administrator
          ansible_password: LabAdmin2024!
        ws01:
          ansible_host: 10.0.20.61
          ansible_user: Admin
          ansible_password: LabAdmin2024!
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_port: 5985
        ansible_winrm_scheme: http
    linux:
      hosts:
        target01:
          ansible_host: 10.0.20.62
          ansible_user: ubuntu
        kali:
          ansible_host: 10.0.20.63
          ansible_user: kali
      vars:
        ansible_connection: ssh
        ansible_ssh_pass: LabAdmin2024!
        ansible_become: true
        ansible_become_password: LabAdmin2024!
    blue:
      hosts:
        splunk:
          ansible_host: 10.0.20.20
          ansible_user: splunk
      vars:
        ansible_connection: ssh
        ansible_become: true
